<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="MonkeyCache.FileStore" Version="1.6.3" />
    <PackageReference Include="Xam.Plugin.Connectivity" Version="3.2.0" />
  </ItemGroup>
</Project>
